### ISSUE TITLE
Add supported interpreter versions to the documentation

### ISSUE THREAD

**Issue by rockdaboot** [elastic/universal-profiling-documentation#21]
Mentioned by @florianl in https://github.com/elastic/prodfiler/pull/2845#pullrequestreview-1198857132.

List of currently supported (tested) versions:
- V8: >= 8.1.0
- JVM/JDK: >= 7
- Perl: >= 5.28 and < 5.35
- PHP: >= 7.3 and < 8.2
- Python: >= 3.6 and < 3.10
- Ruby: >= 2.5 and < 3.0.4

Newer versions may or may not work, depending on how internal interpreter data structures changed.

**Comment by iogbole** [comment]
https://github.com/elastic/universal-profiling-documentation/pull/22
